<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Fintan Cannon" />


<title>Online Retail Dataset</title>

<script src="site_libs/header-attrs-2.12/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Online Retail Dataset</h1>
<h4 class="author">Fintan Cannon</h4>
<h4 class="date">3/9/2022</h4>

</div>


<div id="introduction" class="section level1">
<h1>1. Introduction</h1>
<p>This workbook explores a dataset pertaining to the transactions of a non-store online retailer based in the United Kingdom. This workbook will firsty perform basic data exploration of the dataset and implement add value models focusing on CRM management and consumer purchasing patterns.</p>
<ul>
<li>Variable Summary:
<ul>
<li>InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter ‘c’, it indicates a cancellation.</li>
<li>StockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.</li>
<li>Description: Product (item) name. Nominal.</li>
<li>Quantity: The quantities of each product (item) per transaction. Numeric.</li>
<li>InvoiceDate: Invice Date and time. Numeric, the day and time when each transaction was generated.</li>
<li>UnitPrice: Unit price. Numeric, Product price per unit in sterling.</li>
<li>CustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.</li>
<li>Country: Country name. Nominal, the name of the country where each customer resides.</li>
</ul></li>
</ul>
<div id="goals-for-this-project" class="section level2">
<h2>1.2 Goals for this project</h2>
<p>Analyze data initially to derive insights that typically add value in an online retail context. Features such as stock code, unit price, customer id etc will allow us answer such question as which SKUs and customers drive revenue the most and when are the busiest times of the year for the retailer.</p>
<p>The features present will allow us segment customers by performing a Recency, Frequency and Monetary(RFM) based on their past purchasing behavior. Based on the customer’s segmentation the most optimal add value action can be executed in relation to each respective customer.</p>
<p>Finally, a market basket analysis will be performed to identify which SKUs are frequently purchased together.Knowledge of this will allow for revenue to be maximised by upselling.</p>
</div>
<div id="load-data-and-view-variable-summaries." class="section level2">
<h2>1.3 Load data and view variable summaries.</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&#39;C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">Finta</span><span class="sc">\\</span><span class="st">Downloads</span><span class="sc">\\</span><span class="st">OnlineRetail.csv</span><span class="sc">\\</span><span class="st">OnlineRetail.csv&#39;</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(retail)</span></code></pre></div>
<pre><code>##   InvoiceNo          StockCode         Description           Quantity        
##  Length:541909      Length:541909      Length:541909      Min.   :-80995.00  
##  Class :character   Class :character   Class :character   1st Qu.:     1.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :     3.00  
##                                                           Mean   :     9.55  
##                                                           3rd Qu.:    10.00  
##                                                           Max.   : 80995.00  
##                                                                              
##  InvoiceDate          UnitPrice           CustomerID       Country         
##  Length:541909      Min.   :-11062.06   Min.   :12346    Length:541909     
##  Class :character   1st Qu.:     1.25   1st Qu.:13953    Class :character  
##  Mode  :character   Median :     2.08   Median :15152    Mode  :character  
##                     Mean   :     4.61   Mean   :15288                      
##                     3rd Qu.:     4.13   3rd Qu.:16791                      
##                     Max.   : 38970.00   Max.   :18287                      
##                                         NA&#39;s   :135080</code></pre>
</div>
</div>
<div id="preprocessing" class="section level1">
<h1>2. Preprocessing</h1>
<p>Add additional variables to the data set and standardise the variable names. The additional variables will allow us analyse the data better and will prove useful when building our respective models.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">set_colnames</span>(<span class="fu">names</span>(.) <span class="sc">%&gt;%</span> <span class="fu">to_snake_case</span>())</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_spend =</span> unit_price <span class="sc">*</span> quantity, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">customer_id =</span> <span class="fu">as.character</span>(customer_id),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">invoice_hour =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(<span class="fu">strptime</span>(invoice_date, <span class="st">&quot;%m/%d/%Y %H:%M&quot;</span>),<span class="at">format =</span> <span class="st">&quot;%H&quot;</span>)),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">invoice_date =</span> <span class="fu">as.Date</span>(invoice_date, <span class="at">format =</span> <span class="st">&#39;%m/%d/%Y&#39;</span>),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">invoice_month =</span> <span class="fu">as.factor</span>(<span class="fu">format</span>(invoice_date,<span class="st">&quot;%m&quot;</span>)),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">invoice_day =</span> <span class="fu">as.factor</span>(<span class="fu">format</span>(invoice_date,<span class="st">&quot;%A&quot;</span>)), </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">invoice_week =</span> <span class="fu">as.factor</span>(<span class="fu">format</span>(invoice_date,<span class="st">&quot;%V&quot;</span>)),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">refund =</span> <span class="fu">str_detect</span>(retail<span class="sc">$</span>invoice_no,<span class="st">&quot;^C&quot;</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<ul>
<li>New Variable Notes:
<ul>
<li>refund - Denotes whether observation was canceled transaction and money refunded. Refunds can be identified by having the letter C as the first letter of an observation’s invoice number value.</li>
<li>total_spend - Total revenue for each respective transaction.</li>
</ul></li>
</ul>
<div id="remove-obvious-errors" class="section level2">
<h2>2.1 Remove obvious errors</h2>
<p>Some obvious errors exist such as an extremely large order quantity input which was canceled. Some empty transactions exist which have a unit price of zero and customer id value. The value these observations bring is minimal so are removed.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove obvious transaction errors</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>transaction_errors <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(total_spend <span class="sc">&lt;</span> <span class="sc">-</span><span class="dv">5000</span> <span class="sc">|</span> total_spend <span class="sc">&gt;</span> <span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(total_spend)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="st">`</span><span class="at">%notin%</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">Negate</span>(<span class="st">`</span><span class="at">%in%</span><span class="st">`</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(total_spend <span class="sc">%notin%</span> transaction_errors)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove &#39;empty&#39; transactions: Total spend equals 0.00</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(total_spend <span class="sc">!=</span> <span class="fl">0.00</span>)</span></code></pre></div>
</div>
<div id="non-transactional-records" class="section level2">
<h2>2.2 Non-transactional records</h2>
<p>Using stock code and description variables we can see the rows that contain non-transactional information such as samples.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Non-transactional stock code &amp; description values</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="cf">function</span>(x){</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  j <span class="ot">&lt;-</span> retail[<span class="fu">which</span>(<span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> x),]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="fu">table</span>(j<span class="sc">$</span>description))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>}) </span></code></pre></div>
<pre><code>## [[1]]
## 
## Discount   Manual  SAMPLES 
##       77      563       63 
## 
## [[2]]
## 
## CARRIAGE 
##      143 
## 
## [[3]]
## 
## DOTCOM POSTAGE 
##            707 
## 
## [[4]]
## 
##            CRUK Commission PADS TO MATCH ALL CUSHIONS 
##                         16                          3 
##                    POSTAGE 
##                       1250 
## 
## [[5]]
## 
##  50&#39;S CHRISTMAS GIFT BAG LARGE              DOLLY GIRL BEAKER 
##                            130                            181 
##    I LOVE LONDON MINI BACKPACK    I LOVE LONDON MINI RUCKSACK 
##                             88                              1 
##        NINE DRAWER OFFICE TIDY     OVAL WALL MIRROR DIAMANTE  
##                             34                            161 
## 
## [[6]]
## 
##     4 PURPLE FLOCK DINNER CANDLES  3 BLACK CATS W HEARTS BLANK CARD 
##                                41                                 3 
##   3 GARDENIA MORRIS BOXED CANDLES       3 ROSE MORRIS BOXED CANDLES 
##                                89                               174 
## 3 WHITE CHOC MORRIS BOXED CANDLES      3D DOG PICTURE PLAYING CARDS 
##                               125                                90 
## 
## [[7]]
## 
## EDWARDIAN PARASOL BLACK 
##                     388 
## 
## [[8]]
## 
##          BOXED GLASS ASHTRAY               BOYS PARTY BAG 
##                            4                           11 
##        CAMOUFLAGE DOG COLLAR   HAYNES CAMPER SHOULDER BAG 
##                            1                            1 
##        OOH LA LA DOGS COLLAR SUNJAR LED NIGHT NIGHT LIGHT 
##                            1                            2 
## 
## [[9]]
## 
##      AMAZON FEE GIRLS PARTY BAG 
##               8              13</code></pre>
<p>Counting the most common stock codes according to the number of characters in it. Stock codes with values of D,M,S represent discounts, manual imput and samples respectively.</p>
<p>Stock code characters = 1: Discount, Manual input or Sample.<br />
Stock code characters = 2: ‘carriage’ primarily pertaining to transactions to Ireland.<br />
Stock code characters = 3: Dotcom Postage.<br />
Stock code characters = 4: Postage.<br />
Stock code characters = 7: Unsaleable, destroyed.<br />
Stock code characters = 9: Amazon Fee</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Amazon fee</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>amazon_fee <span class="ot">&lt;-</span> retail[<span class="fu">which</span>(retail<span class="sc">$</span>stock_code <span class="sc">==</span> <span class="st">&#39;AMAZONFEE&#39;</span>),]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>amazon_fee_total <span class="ot">&lt;-</span> amazon_fee <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_amazon_fee =</span> <span class="fu">round</span>(<span class="fu">sum</span>(total_spend))) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(total_amazon_fee) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">comma</span>()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Total Amazon Fee cost</span></span></code></pre></div>
<p>Outgoing expense labeled ‘AMAZONFEE’ totals £-20,207</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Postage</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>postage_fee <span class="ot">&lt;-</span> retail[<span class="fu">which</span>(retail<span class="sc">$</span>stock_code <span class="sc">==</span> <span class="st">&#39;POST&#39;</span>),]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>postage_fee_total <span class="ot">&lt;-</span> postage_fee <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_postage_fee =</span> <span class="fu">round</span>(<span class="fu">sum</span>(total_spend))) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(total_postage_fee) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">comma</span>()</span></code></pre></div>
<p>Revenue labeled ‘POST’ recorded in primarily non UK transactions totals £66,231.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove chosen values</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(stock_code <span class="sc">%notin%</span> <span class="fu">c</span>(<span class="st">&#39;S&#39;</span>,<span class="st">&#39;M&#39;</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail[<span class="sc">-</span><span class="fu">which</span>(retail<span class="sc">$</span>stock_code <span class="sc">==</span> <span class="st">&#39;AMAZONFEE&#39;</span>),]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail[<span class="sc">-</span><span class="fu">which</span>(retail<span class="sc">$</span>stock_code <span class="sc">==</span> <span class="st">&#39;POST&#39;</span>),]</span></code></pre></div>
<p>Removing transactions pertaining to stock code values for samples, manual input, amazon fees and postage.</p>
</div>
<div id="refunds" class="section level2">
<h2>2.3 Refunds</h2>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>refund_per_transaction <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(retail<span class="sc">$</span>refund <span class="sc">==</span> <span class="st">&#39;TRUE&#39;</span>),<span class="dv">3</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>refund_per_transaction</span></code></pre></div>
<pre><code>## [1] 0.016</code></pre>
<p>Total number of refunds per item bought is 0.016</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>refund_invoice <span class="ot">&lt;-</span>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(refund <span class="sc">==</span> <span class="st">&#39;TRUE&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(invoice_no,customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">refund_total =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">refund_total =</span> <span class="fu">abs</span>(refund_total)) <span class="co"># Data frame containing refunded invoices only. </span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>sale_invoice <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(refund <span class="sc">==</span> <span class="st">&#39;FALSE&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(invoice_no,customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">refund_total =</span> <span class="fu">sum</span>(total_spend)) <span class="co"># Data frame containing sales invoices only. </span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Match refunds with sales based off total invoice amount and customer id</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>sale_refund_df <span class="ot">&lt;-</span> sale_invoice <span class="sc">%&gt;%</span> <span class="fu">inner_join</span>(refund_invoice,<span class="at">by =</span> <span class="fu">c</span>(<span class="st">&#39;customer_id&#39;</span>,<span class="st">&#39;refund_total&#39;</span>))</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>sale_refund_invoices <span class="ot">&lt;-</span> <span class="fu">c</span>(sale_refund_df<span class="sc">$</span>invoice_no.x,sale_refund_df<span class="sc">$</span>invoice_no.y) </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Combining sales &amp; refund invoice numbers in one vector</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(invoice_no <span class="sc">==</span> <span class="st">&#39;537217&#39;</span> <span class="sc">|</span> invoice_no <span class="sc">==</span> <span class="st">&#39;C537406&#39;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(invoice_date,invoice_hour,invoice_month, invoice_day,invoice_week))</span></code></pre></div>
<pre><code>##   invoice_no stock_code                    description quantity unit_price
## 1     537217      22849   BREAD BIN, DINER STYLE, MINT        4      14.95
## 2     537217      22847  BREAD BIN, DINER STYLE, IVORY        4      14.95
## 3     537217      22927 GREEN GIANT GARDEN THERMOMETER        4       5.95
## 4     537217      22926 IVORY GIANT GARDEN THERMOMETER        4       5.95
## 5    C537406      22926 IVORY GIANT GARDEN THERMOMETER       -4       5.95
## 6    C537406      22927 GREEN GIANT GARDEN THERMOMETER       -4       5.95
## 7    C537406      22847    BREAD BIN DINER STYLE IVORY       -4      14.95
## 8    C537406      22849     BREAD BIN DINER STYLE MINT       -4      14.95
##   customer_id        country total_spend refund
## 1       15502 United Kingdom        59.8  FALSE
## 2       15502 United Kingdom        59.8  FALSE
## 3       15502 United Kingdom        23.8  FALSE
## 4       15502 United Kingdom        23.8  FALSE
## 5       15502 United Kingdom       -23.8   TRUE
## 6       15502 United Kingdom       -23.8   TRUE
## 7       15502 United Kingdom       -59.8   TRUE
## 8       15502 United Kingdom       -59.8   TRUE</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(invoice_no <span class="sc">%notin%</span> sale_refund_invoices) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Removing invoice numbers pertaining to initial transaction and refund. </span></span></code></pre></div>
<p>Some canceled sales invoices can be matched up with their sales equivalent by matching the customer id and if the absolute value of each invoice is identical.</p>
</div>
<div id="missing-values" class="section level2">
<h2>2.4 Missing values</h2>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Missing Values</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(retail, <span class="cf">function</span>(x){</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  missing <span class="ot">&lt;-</span> <span class="fu">is.na</span>(x)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>(<span class="fu">which</span>(missing <span class="sc">==</span> <span class="st">&#39;TRUE&#39;</span>))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>}) <span class="co">#Function counting the number of missing values in each variable</span></span></code></pre></div>
<pre><code>## $invoice_no
## [1] 0
## 
## $stock_code
## [1] 0
## 
## $description
## [1] 0
## 
## $quantity
## [1] 0
## 
## $invoice_date
## [1] 0
## 
## $unit_price
## [1] 0
## 
## $customer_id
## [1] 132118
## 
## $country
## [1] 0
## 
## $total_spend
## [1] 0
## 
## $invoice_hour
## [1] 0
## 
## $invoice_month
## [1] 0
## 
## $invoice_day
## [1] 0
## 
## $invoice_week
## [1] 0
## 
## $refund
## [1] 0</code></pre>
<p>customer_id is the only variable with missing values</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#customer_id missing values</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">is.na</span>(retail<span class="sc">$</span>customer_id))  </span></code></pre></div>
<pre><code>## [1] 0.2470442</code></pre>
<p>Proportion of missing values in customer_id variable.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total spend comparing existing and missing customer ids</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">missing_cust_id =</span> <span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_spend, <span class="at">fill =</span> missing_cust_id)) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log10&quot;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log2&quot;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total Spend&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Spend by missing and existing customer id&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="st">&#39;Missing Customer Id&#39;</span>)) </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Daily transactions comparing exisiting and missing customer ids</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span>retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">missing_cust_id =</span> <span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(invoice_day, <span class="at">fill =</span> missing_cust_id,<span class="at">label =</span> )) <span class="sc">+</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat =</span> <span class="st">&quot;count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Day&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Transaction Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Transactions by day of the week&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="st">&#39;Missing Customer Id&#39;</span>))</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Country transactions comparing existing and missing customer ids</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span>retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">missing_cust_id =</span> <span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(country, <span class="at">fill =</span> missing_cust_id)) <span class="sc">+</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat =</span> <span class="st">&quot;count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="st">&#39;Missing Customer Id&#39;</span>))</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Month transactions comparing existing and missing customer ids</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">missing_cust_id =</span> <span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(invoice_month, <span class="at">fill =</span> missing_cust_id)) <span class="sc">+</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat =</span> <span class="st">&quot;count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Transaction Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Transactions by month&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="st">&#39;Missing Customer Id&#39;</span>))</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Epoch transactions comparing existing and missing customer ids</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">missing_cust_id =</span> <span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(invoice_week, <span class="at">fill =</span> missing_cust_id)) <span class="sc">+</span></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">stat =</span> <span class="st">&quot;count&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill=</span><span class="fu">guide_legend</span>(<span class="st">&#39;Missing Customer Id&#39;</span>))</span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(m1,m2,m4)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>No discernible reason as to why missing customer id values exist.</p>
</div>
</div>
<div id="exploring-variables" class="section level1">
<h1>3. Exploring Variables</h1>
<div id="invoice_number" class="section level2">
<h2>3.1 Invoice_Number</h2>
<p>Each individual invoice number represents the purchase(s) made by a customer on a given occasion.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>unique_invoices <span class="ot">&lt;-</span> <span class="fu">comma</span>(<span class="fu">length</span>(<span class="fu">unique</span>(retail<span class="sc">$</span>invoice_no)))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of transactions</span></span></code></pre></div>
<p>A total of 22,801 unique invoices contained in this data set</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total spend per invoice</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>invoice_spend <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_no) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_invoice_amount =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_invoice_amount))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(invoice_spend<span class="sc">$</span>total_invoice_amount)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -16459.00     97.09    250.60    435.13    439.23  52940.94</code></pre>
<p>Difference between median and mean caused by a number of high revenue generating invoices.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total spend per invoice histogram</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>invoice_hist <span class="ot">&lt;-</span> invoice_spend <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_invoice_amount)) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(invoice_spend<span class="sc">$</span>total_invoice_amount),        <span class="co"># Add line for mean</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(invoice_spend<span class="sc">$</span>total_invoice_amount),        <span class="co"># Add line for median</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total Invoice Amount&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Invoice Amount Histogram&quot;</span>)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>invoice_hist_log <span class="ot">&lt;-</span> invoice_spend <span class="sc">%&gt;%</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_invoice_amount)) <span class="sc">+</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&#39;log2&#39;</span>, <span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log2&quot;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(invoice_spend<span class="sc">$</span>total_invoice_amount),       </span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span>                                                     <span class="co"># Add line for mean</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(invoice_spend<span class="sc">$</span>total_invoice_amount),        </span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span>                                                     <span class="co"># Add line for median</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total Invoice Amount&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Invoice Amount Histogram - Log 2&quot;</span>) </span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(invoice_hist,invoice_hist_log)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-15-1.png" width="672" /></dt>
<dd>Plot 1: Right skewed distribution of the total invoice amounts; a relatively small number of invoices have much larger total amounts than the median invoice amount. Plot 2: Scaled distribution of total invoice amount using log2.
</dd>
</dl>
<p>Green Line = Mean: 435<br />
Red Line = Median: 250.6</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>invoice_item_quantities <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_no) <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">quantities_bought =</span> <span class="fu">sum</span>(quantity)) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(quantities_bought))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(invoice_item_quantities<span class="sc">$</span>quantities_bought)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -9360.0    35.0   124.0   232.2   264.0 15049.0</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>invoice_item_quantities <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="st">&#39;&#39;</span>,quantities_bought)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Quanties per Invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Quantity of Items per Invoice&quot;</span>) </span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-16-1.png" width="672" /></dt>
<dd>Summarized distribution of quantity of items bought per invoice.
</dd>
</dl>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># number of items bought per transactions</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>invoice_quantities <span class="ot">&lt;-</span> invoice_item_quantities <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(quantities_bought)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(invoice_item_quantities<span class="sc">$</span>quantities_bought),        <span class="co"># Add line for mean</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(invoice_item_quantities<span class="sc">$</span>quantities_bought),        <span class="co"># Add line for median</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantities Bought Per Invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Quantities Per Invoice Histogram&quot;</span>) </span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>invoice_quantities_log <span class="ot">&lt;-</span> invoice_item_quantities <span class="sc">%&gt;%</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(quantities_bought)) <span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&#39;log2&#39;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">&quot;log2&quot;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(invoice_item_quantities<span class="sc">$</span>quantities_bought),        <span class="co"># Add line for mean</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(invoice_item_quantities<span class="sc">$</span>quantities_bought),        <span class="co"># Add line for median</span></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantities Bought Per Invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Quantities Per Invoice Histogram - Log2&quot;</span>) </span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(invoice_quantities,invoice_quantities_log)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="stock-code" class="section level2">
<h2>3.2 Stock Code</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="do">## stock_code</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>sku_num <span class="ot">&lt;-</span> <span class="fu">comma</span>(<span class="fu">length</span>(<span class="fu">unique</span>(retail<span class="sc">$</span>stock_code))) <span class="co">#Number of SKUS</span></span></code></pre></div>
<p>Number of unique SKUs is 3,930</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SKU sales count</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sku_sales_count <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> <span class="dv">6</span> <span class="sc">|</span><span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> <span class="dv">7</span> <span class="sc">|</span> <span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(stock_code)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sku_sales_count<span class="sc">$</span>n)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     1.0    17.0    66.0   136.5   171.0  2290.0</code></pre>
<p>Summary of individual SKU sales count</p>
<p>*Note: Sales count in this context denotes how often an indivual stock code was included in an invoice.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#SKU sales distribution</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>sku_sales_count  <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(stock_code,n),n)) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>,<span class="at">position=</span><span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y=</span><span class="fu">element_blank</span>(),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.y=</span><span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Stock Code&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;SKU Invoice Inclusion&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;SKU Invoice Inclusion Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)<span class="co"># Conforms strongly to the power rule </span></span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>SKU purchase distribution conforms strongly to the power rule; a small number of SKUs account for a large percentage of overall SKUs sold.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SKU sales distribution by quantile - Mosaic graph</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sku_sales_count  <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">stock_quant =</span> <span class="fu">ntile</span>(<span class="fu">rank</span>(n),<span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(stock_quant) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_quantile_count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">items_sold_proportion =</span> <span class="fu">round</span>(total_quantile_count<span class="sc">/</span><span class="fu">sum</span>(total_quantile_count),<span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">area =</span> total_quantile_count, <span class="at">fill =</span> stock_quant, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">&#39;Q&#39;</span>,stock_quant,<span class="st">&#39;</span><span class="sc">\n\n</span><span class="st">&#39;</span>,items_sold_proportion)))<span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap</span>() <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap_text</span>(<span class="at">colour =</span> <span class="st">&quot;Black&quot;</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">place =</span> <span class="st">&quot;centre&quot;</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size =</span> <span class="dv">20</span>,</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">option=</span><span class="st">&quot;mako&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Quantile Sales Count Proportion&quot;</span>)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-21-1.png" width="672" /></dt>
<dd>Each SKU is allocated a quantile based on its respective sales count with the top selling SKUs assigned to Q10.
</dd>
</dl>
<p>The top 10% selling SKUs account for 45% of total SKUs sold.<br />
The top 20% selling SKUs account for 65% of total SKUs sold.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Most popular skus</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>popular_stock_code <span class="ot">&lt;-</span> sku_sales_count <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(n,<span class="at">n =</span> <span class="dv">20</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>popular_stock_code <span class="ot">&lt;-</span> popular_stock_code <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(retail) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(stock_code,description,n) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">total_spend =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_spend <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">&#39;total_transaction_number&#39;</span> <span class="ot">=</span> n)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>popular_stock_code[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,]</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
## # Groups:   stock_code, description [2]
##   stock_code description                        total_transaction_n~ total_spend
##   &lt;chr&gt;      &lt;chr&gt;                                             &lt;int&gt;       &lt;dbl&gt;
## 1 85123A     CREAM HANGING HEART T-LIGHT HOLDER                 2290        179.
## 2 85123A     WHITE HANGING HEART T-LIGHT HOLDER                 2290      97610.</code></pre>
<p>Some stock codes have more than one corresponding description as can be seen above with the highest selling SKU.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>popular_stock_code <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(total_transaction_number) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_transaction_number,<span class="fu">fct_inorder</span>(description))) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Count of SKUs included in an invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;SKU Description&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Most Popular SKUs&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-23-1.png" width="672" /></dt>
<dd>Some stock codes have more than one corresponding description as can be seen above with the highest selling SKU.
</dd>
</dl>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Most profitable skus</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>profitable_stock_code <span class="ot">&lt;-</span> popular_stock_code <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(retail) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(stock_code,description,total_transaction_number) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">total_spend =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_spend <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_spend))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>profitable_stock_code</span></code></pre></div>
<pre><code>## # A tibble: 26 x 4
## # Groups:   stock_code, description [26]
##    stock_code description                          total_transactio~ total_spend
##    &lt;chr&gt;      &lt;chr&gt;                                            &lt;int&gt;       &lt;dbl&gt;
##  1 22423      &quot;REGENCY CAKESTAND 3 TIER&quot;                        2163     162625.
##  2 47566      &quot;PARTY BUNTING&quot;                                   1714      98244.
##  3 85123A     &quot;WHITE HANGING HEART T-LIGHT HOLDER&quot;              2290      97610.
##  4 85099B     &quot;JUMBO BAG RED RETROSPOT&quot;                         2142      92356.
##  5 22086      &quot;PAPER CHAIN KIT 50&#39;S CHRISTMAS &quot;                 1195      63486.
##  6 84879      &quot;ASSORTED COLOUR BIRD ORNAMENT&quot;                   1495      58960.
##  7 22386      &quot;JUMBO BAG PINK POLKADOT&quot;                         1240      41600.
##  8 22720      &quot;SET OF 3 CAKE TINS PANTRY DESIGN &quot;               1461      37428.
##  9 22960      &quot;JAM MAKING SET WITH JARS&quot;                        1218      36116.
## 10 20725      &quot;LUNCH BAG RED RETROSPOT&quot;                         1629      34897.
## # ... with 16 more rows</code></pre>
<p>Highest revenue generating SKUs</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>profitable_stock_code <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(total_spend) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_spend,<span class="fu">fct_inorder</span>(description))) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Total Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;SKU Description&quot;</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Most Profitable SKUs&quot;</span>) <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Non performing SKUs</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>non_performing_skus <span class="ot">&lt;-</span> sku_sales_count <span class="sc">%&gt;%</span> <span class="fu">filter</span>(n <span class="sc">&lt;</span> <span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(retail) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_spend <span class="sc">&lt;</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(stock_code,description) <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">stock_code_revenue =</span> <span class="fu">sum</span>(total_spend),<span class="at">number_of_basket_entries =</span> <span class="fu">n</span>())</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>non_performing_skus_nrow <span class="ot">&lt;-</span> non_performing_skus <span class="sc">%&gt;%</span> <span class="fu">nrow</span>()</span></code></pre></div>
<p>367 SKUs have a total revenue of under £50.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># frequently returned stock items </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> <span class="dv">6</span> <span class="sc">|</span><span class="fu">nchar</span>(retail<span class="sc">$</span>stock_code) <span class="sc">==</span> <span class="dv">7</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(refund <span class="sc">==</span> <span class="st">&#39;TRUE&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(stock_code) <span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">6</span>)</span></code></pre></div>
<pre><code>##   stock_code  n
## 1     85099B 37
## 2     85123A 35
## 3     75049L 20
## 4     82494L 13
## 5     85159B 13
## 6     79191C 12</code></pre>
</div>
<div id="quantity" class="section level2">
<h2>3.3 Quantity</h2>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(retail<span class="sc">$</span>quantity)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -9360.0     1.0     3.0     9.9    10.0  4800.0</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Distribution of SKU quantities purchased in a transaction</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(quantity <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(quantity)) <span class="sc">+</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&#39;log2&#39;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(retail<span class="sc">$</span>quantity),        <span class="co"># Add line for mean</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">median</span>(retail<span class="sc">$</span>quantity),        <span class="co"># Add line for median</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">lwd =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantities of SKUs bought&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;SKU Quantities Bought&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-29-1.png" width="672" /></dt>
<dd>Green Line = Mean: 10<br />
Red Line = Median: 3
</dd>
</dl>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>quantities_sold_per_invoice <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_no) <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_quantities_sold =</span> <span class="fu">sum</span>(quantity))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>quantities_sold_per_invoice <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_quantities_sold)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">trans =</span> <span class="st">&#39;log2&#39;</span>,<span class="at">labels =</span> comma) <span class="sc">+</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Quantity Per Invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Quantity Count Per Invoice&quot;</span>) <span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
</div>
<div id="customer-id" class="section level2">
<h2>3.4 Customer ID</h2>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">is.na</span>(retail<span class="sc">$</span>customer_id))</span></code></pre></div>
<pre><code>## [1] 0.2470442</code></pre>
<p>Total proportion of missing ids is 0.2470442</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(retail<span class="sc">$</span>customer_id))</span></code></pre></div>
<pre><code>## [1] 4352</code></pre>
<p>Total number of unique customer ids is 4352</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>customer_spend <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_customer_spend =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_customer_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion_of_total_spend =</span> total_customer_spend<span class="sc">/</span><span class="fu">sum</span>(total_customer_spend))</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>customer_spend <span class="sc">%&gt;%</span> <span class="fu">top_n</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    customer_id total_customer_spend proportion_of_total_spend
##    &lt;chr&gt;                      &lt;dbl&gt;                     &lt;dbl&gt;
##  1 14646                    278572.                   0.0339 
##  2 18102                    259657.                   0.0316 
##  3 17450                    182506.                   0.0222 
##  4 14911                    128222.                   0.0156 
##  5 12415                    123638.                   0.0150 
##  6 14156                    114505.                   0.0139 
##  7 17511                     88138.                   0.0107 
##  8 16684                     65892.                   0.00801
##  9 13694                     62677.                   0.00762
## 10 15311                     59444.                   0.00723</code></pre>
<p>Highest revenue customers and their proportion of overall revenue.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Customer spend by quantile</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>customer_spend <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">quantile =</span> <span class="fu">ntile</span>(<span class="fu">rank</span>(total_customer_spend),<span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(quantile) <span class="sc">%&gt;%</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_spend =</span> <span class="fu">sum</span>(total_customer_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_of_sales =</span> total_spend<span class="sc">/</span><span class="fu">sum</span>(total_spend),<span class="at">percent_of_sales =</span> scales<span class="sc">::</span><span class="fu">percent</span>(percent_of_sales),<span class="at">total_spend =</span> total_spend<span class="sc">/</span><span class="dv">1000000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">area =</span> total_spend,<span class="at">fill =</span> quantile,<span class="at">label =</span> <span class="fu">paste</span>(percent_of_sales, <span class="fu">round</span>(total_spend,<span class="at">digits =</span> <span class="dv">2</span>),<span class="fu">paste</span>(<span class="st">&#39;Q&#39;</span>,quantile), <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>))) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap</span>() <span class="sc">+</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap_text</span>(<span class="at">colour =</span> <span class="st">&quot;Black&quot;</span>,</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">place =</span> <span class="st">&quot;centre&quot;</span>,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size =</span> <span class="dv">20</span>,</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">option=</span><span class="st">&quot;mako&quot;</span>)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-34-1.png" width="672" /></dt>
<dd>Line 1: Percentage of Revenue.<br />
Line 2: Revenue in millions.<br />
Line 3: Quantile.
</dd>
</dl>
<p>The top 20% of customers account for around 73% of total revenue.</p>
</div>
<div id="country" class="section level2">
<h2>3.5 Country</h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(retail<span class="sc">$</span>country))</span></code></pre></div>
<pre><code>## [1] 38</code></pre>
<p>Number of countries sold to.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>customer_country <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">select</span>(customer_id,country) <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">country =</span> <span class="fu">unique</span>(country))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(customer_country<span class="sc">$</span>country)</span></code></pre></div>
<pre><code>## 
##            Australia              Austria              Bahrain 
##                    9                   11                    2 
##              Belgium               Brazil               Canada 
##                   25                    1                    4 
##      Channel Islands               Cyprus       Czech Republic 
##                    9                    7                    1 
##              Denmark                 EIRE   European Community 
##                    9                    4                    1 
##              Finland               France              Germany 
##                   12                   88                   95 
##               Greece            Hong Kong              Iceland 
##                    4                    1                    1 
##               Israel                Italy                Japan 
##                    5                   14                    8 
##              Lebanon            Lithuania                Malta 
##                    1                    1                    2 
##          Netherlands               Norway               Poland 
##                    9                   10                    6 
##             Portugal                  RSA         Saudi Arabia 
##                   20                    1                    1 
##            Singapore                Spain               Sweden 
##                    1                   29                    8 
##          Switzerland United Arab Emirates       United Kingdom 
##                   22                    2                 3935 
##          Unspecified                  USA 
##                    5                    2</code></pre>
<p>Number of customers per country</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">spend_per_country =</span> <span class="fu">round</span>(<span class="fu">sum</span>(total_spend))) <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> <span class="fu">round</span>(spend_per_country<span class="sc">/</span><span class="fu">sum</span>(spend_per_country),<span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">area =</span> spend_per_country, <span class="at">fill =</span> country, <span class="at">label =</span> <span class="fu">paste</span>(country,<span class="fu">comma</span>(spend_per_country),prop,<span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>))) <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap</span>() <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap_text</span>(<span class="at">colour =</span> <span class="st">&quot;Black&quot;</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">place =</span> <span class="st">&quot;centre&quot;</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size =</span> <span class="dv">20</span>,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-37-1.png" width="672" /></dt>
<dd>Line 1: Country.<br />
Line 2: Total Revenue.<br />
Line 3: Proportion of Revenue.
</dd>
</dl>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Non UK Country Spend</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">!=</span> <span class="st">&#39;United Kingdom&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">spend_per_country =</span> <span class="fu">round</span>(<span class="fu">sum</span>(total_spend))) <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(spend_per_country) <span class="sc">%&gt;%</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(country),spend_per_country)) <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">trans =</span> <span class="st">&#39;log2&#39;</span>) <span class="sc">+</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Revenue Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Revenue Per Non-UK Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Customers per country</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">no_of_customers =</span> <span class="fu">length</span>(<span class="fu">unique</span>(customer_id))) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(no_of_customers) <span class="sc">%&gt;%</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(country),no_of_customers)) <span class="sc">+</span></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Customers Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Customers Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Customers per country minus UK</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">!=</span> <span class="st">&#39;United Kingdom&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">no_of_customers =</span> <span class="fu">length</span>(<span class="fu">unique</span>(customer_id))) <span class="sc">%&gt;%</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(no_of_customers) <span class="sc">%&gt;%</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(country),no_of_customers)) <span class="sc">+</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Customers Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Customers Per Non-UK Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Invoices per country</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">invoices_per_country =</span> <span class="fu">length</span>(<span class="fu">unique</span>(invoice_no))) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(invoices_per_country) <span class="sc">%&gt;%</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(country),invoices_per_country)) <span class="sc">+</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Invoices Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Invoices Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Invoices per country minus UK</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(country <span class="sc">!=</span> <span class="st">&#39;United Kingdom&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">invoices_per_country =</span> <span class="fu">length</span>(<span class="fu">unique</span>(invoice_no))) <span class="sc">%&gt;%</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(invoices_per_country) <span class="sc">%&gt;%</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(country),invoices_per_country)) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Invoices Per Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Invoices Per Non-UK Country&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
</div>
<div id="time-series" class="section level2">
<h2>4. Time Series</h2>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(retail<span class="sc">$</span>invoice_date)</span></code></pre></div>
<pre><code>## [1] &quot;2010-12-01&quot; &quot;2011-12-09&quot;</code></pre>
<p>Incomplete calender year for 2011 so dates should range from Dec 2010 to Nov 2011</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>calender_year_sales <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">between</span>(invoice_date,<span class="fu">as.Date</span>(<span class="st">&#39;2010-12-01&#39;</span>),<span class="fu">as.Date</span>(<span class="st">&#39;2011-11-30&#39;</span>)))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(calender_year_sales<span class="sc">$</span>invoice_date)</span></code></pre></div>
<pre><code>## [1] &quot;2010-12-01&quot; &quot;2011-11-30&quot;</code></pre>
<p>Remove dates non pertinent to the above range.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>epoch_summary <span class="ot">&lt;-</span> calender_year_sales <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(invoice_week) <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_weekly_earnings =</span> <span class="fu">sum</span>(total_spend),</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">weekly_transactions_no =</span> <span class="fu">length</span>(<span class="fu">unique</span>(invoice_no)))</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>epoch_summary_ordered <span class="ot">&lt;-</span> epoch_summary[<span class="fu">c</span>(<span class="dv">48</span><span class="sc">:</span><span class="dv">51</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">47</span>),]</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>epoch_summary_scaled <span class="ot">&lt;-</span> epoch_summary_ordered <span class="sc">%&gt;%</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_weekly_earnings =</span> <span class="fu">scale</span>(total_weekly_earnings),</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">weekly_transactions_no =</span> <span class="fu">scale</span>(weekly_transactions_no))</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(epoch_summary_ordered)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   invoice_week total_weekly_earnings weekly_transactions_no
##   &lt;fct&gt;                        &lt;dbl&gt;                  &lt;int&gt;
## 1 48                         365926.                    874
## 2 49                         308210.                    606
## 3 50                         204954.                    540
## 4 51                          88393.                    199
## 5 01                         127541.                    281
## 6 02                         182902.                    301</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(epoch_summary_scaled)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##   invoice_week total_weekly_earnings[,1] weekly_transactions_no[,1]
##   &lt;fct&gt;                            &lt;dbl&gt;                      &lt;dbl&gt;
## 1 48                              2.45                        3.29 
## 2 49                              1.67                        1.31 
## 3 50                              0.265                       0.822
## 4 51                             -1.32                       -1.69 
## 5 01                             -0.789                      -1.09 
## 6 02                             -0.0354                     -0.942</code></pre>
<p>Data frames detailing both scaled and total weekly revenue and number of transactions(invoices recorded)</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>epoch_summary_scaled <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(factor,value,<span class="sc">-</span>invoice_week) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">factor =</span> <span class="fu">as.factor</span>(factor)) <span class="sc">%&gt;%</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">factor =</span> <span class="fu">recode_factor</span>(factor,<span class="at">total_weekly_earnings =</span> <span class="st">&#39;Weekly Revenue&#39;</span>,<span class="at">weekly_transactions_no =</span> <span class="st">&#39;Weekly Transactions&#39;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(invoice_week),value,<span class="at">group=</span> factor,<span class="at">color =</span> factor)) <span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span><span class="fu">guide_legend</span>(<span class="st">&#39;&#39;</span>)) <span class="sc">+</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Z Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Invoice Week&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Transaction and Revenue Weekly Distribution&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-46-1.png" width="672" /></dt>
<dd>Weekly revenue heavily correlated with the number of transactions.<br />
Week 37 to 41 sees a divergence from this correlation. Possible that some wholesalers place large revenue generating orders during this window.
</dd>
</dl>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>epoch_summary_earnings <span class="ot">&lt;-</span> epoch_summary_ordered <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(invoice_week,total_weekly_earnings) <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(total_weekly_earnings,value,<span class="sc">-</span>invoice_week) <span class="sc">%&gt;%</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(invoice_week),value,<span class="at">group =</span> total_weekly_earnings)) <span class="sc">+</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Invoice Week&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Weekly Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>epoch_summary_earnings</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-47-1.png" width="672" /></dt>
<dd>Invoice revenue per week.
</dd>
</dl>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total sales by month</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>monthly_earnings <span class="ot">&lt;-</span> calender_year_sales <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_month) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">earnings_by_month =</span> <span class="fu">sum</span>(total_spend))</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>monthly_earnings <span class="ot">&lt;-</span> monthly_earnings[<span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>),]</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>monthly_earnings <span class="sc">%&gt;%</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">fct_inorder</span>(invoice_month),earnings_by_month,<span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Invoice Month&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Montly Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> comma)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
</div>
</div>
<div id="rfm-analysis" class="section level1">
<h1>5. RFM Analysis</h1>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>arb_date <span class="ot">&lt;-</span> <span class="fu">max</span>(retail<span class="sc">$</span>invoice_date) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>rfm_retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(invoice_no,customer_id,invoice_date) <span class="sc">%&gt;%</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_spend =</span> <span class="fu">sum</span>(total_spend))</span></code></pre></div>
<p>Prepare data frame for RFM analysis by removing rows with missing customer id values.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RFM Table</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>rfm_data  <span class="ot">&lt;-</span> <span class="fu">rfm_table_order</span>(</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> rfm_retail,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">customer_id =</span> customer_id,</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">order_date =</span> invoice_date,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">revenue =</span> total_spend,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">analysis_date =</span> arb_date,</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">recency_bins =</span> <span class="dv">5</span>,</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">frequency_bins =</span> <span class="dv">5</span>,</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">monetary_bins =</span> <span class="dv">5</span>,</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>rfm_data[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,]</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   customer_id date_most_recent recency_days transaction_count amount
##   &lt;chr&gt;       &lt;date&gt;                  &lt;dbl&gt;             &lt;dbl&gt;  &lt;dbl&gt;
## 1 12347       2011-12-07                  3                 7  4310 
## 2 12348       2011-09-25                 76                 4  1437.
## 3 12349       2011-11-21                 19                 1  1458.
## 4 12350       2011-02-02                311                 1   294.
## 5 12352       2011-11-03                 37                 5  1145.
## 6 12353       2011-05-19                205                 1    89 
## # ... with 4 more variables: recency_score &lt;int&gt;, frequency_score &lt;int&gt;,
## #   monetary_score &lt;int&gt;, rfm_score &lt;dbl&gt;</code></pre>
<p>Assign RFM score to each customer id.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign segments names</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>segment_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Champions&quot;</span>, <span class="st">&quot;Loyal Customers&quot;</span>, <span class="st">&quot;Potential Loyalist&quot;</span>,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;New Customers&quot;</span>, <span class="st">&quot;Promising&quot;</span>, <span class="st">&quot;Need Attention&quot;</span>, <span class="st">&quot;About To Sleep&quot;</span>,</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                   <span class="st">&quot;At Risk&quot;</span>, <span class="st">&quot;Can&#39;t Lose Them&quot;</span>, <span class="st">&quot;Hibernating&quot;</span>, <span class="st">&quot;Lost&quot;</span>)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign classification rules for segments</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>recency_lower   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>recency_upper   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>frequency_lower <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>frequency_upper <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>monetary_lower  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>monetary_upper  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>segments <span class="ot">&lt;-</span> <span class="fu">rfm_segment</span>(rfm_data, segment_names, recency_lower, recency_upper,</span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>                        frequency_lower, frequency_upper, monetary_lower, monetary_upper)</span></code></pre></div>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine customer segmentation with main data frame</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>combined_rfm_df <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(segments) <span class="sc">%&gt;%</span> </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(customer_id,total_spend,segment,rfm_score,recency_score,frequency_score,monetary_score,stock_code)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>combined_rfm_df <span class="ot">&lt;-</span> combined_rfm_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(customer_id) <span class="sc">%&gt;%</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_spend =</span> <span class="fu">sum</span>(total_spend),<span class="at">segment =</span> <span class="fu">unique</span>(segment),<span class="at">rfm_score =</span> <span class="fu">unique</span>(rfm_score),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">recency_score =</span> <span class="fu">unique</span>(recency_score),<span class="at">frequency_score =</span> <span class="fu">unique</span>(frequency_score), <span class="at">monetary_score =</span> <span class="fu">unique</span>(monetary_score))</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>combined_rfm_df</span></code></pre></div>
<pre><code>## # A tibble: 4,352 x 7
##    customer_id total_spend segment         rfm_score recency_score frequency_score
##    &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt;         &lt;int&gt;           &lt;int&gt;
##  1 12347             4310  Champions             555             5               5
##  2 12348             1437. Loyal Customers       244             2               4
##  3 12349             1458. Others                414             4               1
##  4 12350              294. Others                112             1               1
##  5 12352             1145. Loyal Customers       344             3               4
##  6 12353               89  Lost                  111             1               1
##  7 12354             1079. Others                114             1               1
##  8 12355              459. Others                112             1               1
##  9 12356             2487. Loyal Customers       435             4               3
## 10 12357             6208. Others                315             3               1
## # ... with 4,342 more rows, and 1 more variable: monetary_score &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count of customers per section</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>combined_rfm_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(segment) <span class="sc">%&gt;%</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">spend =</span> <span class="fu">round</span>(<span class="fu">sum</span>(total_spend)))</span></code></pre></div>
<pre><code>## # A tibble: 8 x 3
##   segment            count   spend
##   &lt;chr&gt;              &lt;int&gt;   &lt;dbl&gt;
## 1 About To Sleep       317   74833
## 2 At Risk              552  530908
## 3 Champions            957 5561999
## 4 Lost                 319   39460
## 5 Loyal Customers      365  673955
## 6 Need Attention       121   83678
## 7 Others               724  882363
## 8 Potential Loyalist   996  380382</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>segment_count <span class="ot">&lt;-</span> combined_rfm_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(segment) <span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">spend =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(count) <span class="sc">%&gt;%</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(count,<span class="fu">fct_inorder</span>(segment))) <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Segment&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Segment Count&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma)</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>segment_spend <span class="ot">&lt;-</span> combined_rfm_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(customer_id)) <span class="sc">%&gt;%</span></span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(segment) <span class="sc">%&gt;%</span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>(), <span class="at">spend =</span> <span class="fu">sum</span>(total_spend)) <span class="sc">%&gt;%</span></span>
<span id="cb82-15"><a href="#cb82-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(spend) <span class="sc">%&gt;%</span></span>
<span id="cb82-16"><a href="#cb82-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(spend,<span class="fu">fct_inorder</span>(segment))) <span class="sc">+</span></span>
<span id="cb82-17"><a href="#cb82-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb82-18"><a href="#cb82-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Segment&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-19"><a href="#cb82-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-20"><a href="#cb82-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Total Segment Revenue&quot;</span>) <span class="sc">+</span></span>
<span id="cb82-21"><a href="#cb82-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> comma)</span>
<span id="cb82-22"><a href="#cb82-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-23"><a href="#cb82-23" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(segment_count,segment_spend) </span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
</div>
<div id="market-basket-analysis" class="section level1">
<h1>6. Market Basket Analysis</h1>
<div id="feature-description" class="section level2">
<h2>6.1 Feature: Description</h2>
<p>Model to identify what products are likely to be purchased together and be used to develop or optimize cross selling initiatives on retail sites.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preprocess data for basket analysis - Description</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>retail_basket <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(refund <span class="sc">==</span> <span class="st">&#39;FALSE&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(invoice_no,description)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>retail_basket <span class="ot">&lt;-</span> retail_basket <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_no) <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">cur_group_id</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, description) <span class="co"># Assign basket variable as a key. </span></span></code></pre></div>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert data to class transaction</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>retail_list <span class="ot">&lt;-</span> <span class="fu">split</span>(retail<span class="sc">$</span>description,retail_basket<span class="sc">$</span>id) <span class="co"># Group items according the basket they belong to</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>retail_trans <span class="ot">&lt;-</span> <span class="fu">as</span>(retail_list,<span class="st">&#39;transactions&#39;</span>) <span class="co">#Convert list to transactions</span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>retail_rules <span class="ot">&lt;-</span> <span class="fu">apriori</span>(retail_trans, <span class="at">parameter=</span><span class="fu">list</span>(<span class="at">supp=</span><span class="fl">0.007</span>, <span class="at">conf=</span><span class="fl">0.4</span>)) <span class="co"># Create rule object</span></span></code></pre></div>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.4    0.1    1 none FALSE            TRUE       5   0.007      1
##  maxlen target  ext
##      10  rules TRUE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 136 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[4033 item(s), 19503 transaction(s)] done [0.28s].
## sorting and recoding items ... [1187 item(s)] done [0.01s].
## creating transaction tree ... done [0.01s].
## checking subsets of size 1 2 3 4 5 done [0.09s].
## writing ... [1962 rule(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualise rules</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(retail_rules)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-56-1.png" width="672" /></dt>
<dd>Support: The percentage of transactions that contain all of the items in an itemset.<br />
Confidence: The probability that a transaction that contains the items on the left hand side of the rule also contains the item on the right hand side.<br />
Lift: The increase in likelihood of the right hand side item of the rule being purchased given the left hand side item(s) of the rule are purchased.
</dd>
</dl>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect rules</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">head</span>(<span class="fu">sort</span>(retail_rules,<span class="at">by=</span><span class="st">&#39;lift&#39;</span>),<span class="dv">35</span>))</span></code></pre></div>
<pre><code>##      lhs                        rhs                        support confidence    coverage     lift count
## [1]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007075834  0.9787234 0.007229657 80.20186   138
## [2]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER ROSEMARY,                                                                             
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007537302  0.9735099 0.007742399 79.77464   147
## [3]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER PARSLEY}  0.007127109  0.9720280 0.007332205 79.65320   139
## [4]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.007537302  0.9545455 0.007896221 78.88347   147
## [5]  {HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER CHIVES }  0.007127109  0.8424242 0.008460237 78.61148   139
## [6]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.007537302  0.9607843 0.007844947 78.40241   147
## [7]  {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007844947  0.9562500 0.008203866 78.36027   153
## [8]  {HERB MARKER BASIL,                                                                                
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.007844947  0.9444444 0.008306414 78.04873   153
## [9]  {HERB MARKER BASIL,                                                                                
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.007434754  0.9415584 0.007896221 77.81023   145
## [10] {HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.007896221  0.9333333 0.008460237 77.13051   154
## [11] {HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER CHIVES }  0.007075834  0.8263473 0.008562785 77.11125   138
## [12] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.007742399  0.9437500 0.008203866 77.01237   151
## [13] {HERB MARKER BASIL,                                                                                
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.007434754  0.9415584 0.007896221 76.83353   145
## [14] {HERB MARKER BASIL,                                                                                
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.007844947  0.9386503 0.008357689 76.59622   153
## [15] {HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY,                                                                             
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007896221  0.9333333 0.008460237 76.48235   154
## [16] {HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY,                                                                             
##       HERB MARKER THYME}     =&gt; {HERB MARKER CHIVES }  0.007537302  0.8166667 0.009229349 76.20789   147
## [17] {HERB MARKER BASIL,                                                                                
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007332205  0.9285714 0.007896221 76.09214   143
## [18] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER PARSLEY}  0.007896221  0.9277108 0.008511511 76.02162   154
## [19] {HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.009229349  0.9183673 0.010049736 75.89372   180
## [20] {HERB MARKER MINT,                                                                                 
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.008562785  0.9226519 0.009280623 75.60706   167
## [21] {HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.007896221  0.9221557 0.008562785 75.25022   154
## [22] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.007742399  0.9096386 0.008511511 75.17238   151
## [23] {HERB MARKER BASIL,                                                                                
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER PARSLEY}  0.007229657  0.9155844 0.007896221 75.02791   141
## [24] {HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.008460237  0.9065934 0.009331898 74.92073   165
## [25] {HERB MARKER BASIL,                                                                                
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER THYME}    0.008614059  0.9032258 0.009536994 74.64243   168
## [26] {HERB MARKER BASIL,                                                                                
##       HERB MARKER ROSEMARY,                                                                             
##       HERB MARKER THYME}     =&gt; {HERB MARKER PARSLEY}  0.007844947  0.9107143 0.008614059 74.62883   153
## [27] {HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.009229349  0.9137056 0.010101010 74.56067   180
## [28] {HERB MARKER BASIL,                                                                                
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.008614059  0.9130435 0.009434446 74.50664   168
## [29] {HERB MARKER MINT,                                                                                 
##       HERB MARKER THYME}     =&gt; {HERB MARKER ROSEMARY} 0.008460237  0.9116022 0.009280623 74.38903   165
## [30] {HERB MARKER BASIL,                                                                                
##       HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY}   =&gt; {HERB MARKER THYME}    0.007332205  0.8993711 0.008152592 74.32387   143
## [31] {HERB MARKER MINT,                                                                                 
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER PARSLEY}  0.008460237  0.9065934 0.009331898 74.29114   165
## [32] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER MINT}      =&gt; {HERB MARKER PARSLEY}  0.007947495  0.9064327 0.008767882 74.27797   155
## [33] {HERB MARKER MINT,                                                                                 
##       HERB MARKER PARSLEY}   =&gt; {HERB MARKER CHIVES }  0.007947495  0.7948718 0.009998462 74.17409   155
## [34] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER ROSEMARY}  =&gt; {HERB MARKER MINT}     0.007127109  0.9025974 0.007896221 73.96369   139
## [35] {HERB MARKER CHIVES ,                                                                              
##       HERB MARKER PARSLEY,                                                                              
##       HERB MARKER THYME}     =&gt; {HERB MARKER MINT}     0.007075834  0.9019608 0.007844947 73.91152   138</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>retail_hi_lift <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(retail_rules, <span class="at">by =</span> <span class="st">&#39;lift&#39;</span>),<span class="dv">50</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(retail_hi_lift,<span class="at">method =</span> <span class="st">&#39;graph&#39;</span>,<span class="at">col =</span> <span class="st">&#39;blue&#39;</span>,<span class="at">cex =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Available control parameters (with default values):
## layout    =  stress
## circular  =  FALSE
## ggraphdots    =  NULL
## edges     =  &lt;environment&gt;
## nodes     =  &lt;environment&gt;
## nodetext  =  &lt;environment&gt;
## colors    =  c(&quot;#EE0000FF&quot;, &quot;#EEEEEEFF&quot;)
## engine    =  ggplot2
## max   =  100
## verbose   =  FALSE</code></pre>
<p><img src="project_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemFrequencyPlot</span>(retail_trans,<span class="at">topN=</span><span class="dv">30</span>,<span class="at">type =</span> <span class="st">&#39;absolut&#39;</span>,<span class="at">horiz =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<dl>
<dt><img src="project_files/figure-html/unnamed-chunk-59-1.png" width="672" /></dt>
<dd>Most frequently purchased items.<br />
## 6.2 Feature: Stock Code
</dd>
</dl>
<p>Model is applied in the same way except the variable now used in stock code.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preprocess data for basket analysis - Stock Code</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>retail_basket_stock <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> <span class="fu">filter</span>(refund <span class="sc">==</span> <span class="st">&#39;FALSE&#39;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(invoice_no,stock_code)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>retail_basket_stock <span class="ot">&lt;-</span> retail_basket_stock <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(invoice_no) <span class="sc">%&gt;%</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">cur_group_id</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, stock_code) <span class="co"># Assign basket variable as a key. </span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(retail_basket_stock)</span></code></pre></div>
<pre><code>##        id         stock_code       
##  Min.   :    1   Length:527223     
##  1st Qu.: 4836   Class :character  
##  Median :10324   Mode  :character  
##  Mean   :10058                     
##  3rd Qu.:15171                     
##  Max.   :19503</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert data to class transaction</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>retail_list_stock <span class="ot">&lt;-</span> <span class="fu">split</span>(retail<span class="sc">$</span>stock_code,retail_basket_stock<span class="sc">$</span>id) <span class="co"># Group items according the basket they belong to</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>retail_trans_stock <span class="ot">&lt;-</span> <span class="fu">as</span>(retail_list_stock,<span class="st">&#39;transactions&#39;</span>) <span class="co">#Convert list to transactions</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>retail_rules_stock <span class="ot">&lt;-</span> <span class="fu">apriori</span>(retail_trans_stock, <span class="at">parameter=</span><span class="fu">list</span>(<span class="at">supp=</span><span class="fl">0.007</span>, <span class="at">conf=</span><span class="fl">0.4</span>)) <span class="co"># Create rule object</span></span></code></pre></div>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.4    0.1    1 none FALSE            TRUE       5   0.007      1
##  maxlen target  ext
##      10  rules TRUE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 136 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[3930 item(s), 19503 transaction(s)] done [0.31s].
## sorting and recoding items ... [1185 item(s)] done [0.01s].
## creating transaction tree ... done [0.01s].
## checking subsets of size 1 2 3 4 5 done [0.11s].
## writing ... [2345 rule(s)] done [0.00s].
## creating S4 object  ... done [0.01s].</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualise rules</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(retail_rules_stock)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect rules</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(<span class="fu">head</span>(<span class="fu">sort</span>(retail_rules_stock,<span class="at">by=</span><span class="st">&#39;lift&#39;</span>),<span class="dv">35</span>))</span></code></pre></div>
<pre><code>##      lhs                      rhs     support     confidence coverage   
## [1]  {22916, 22919, 22921} =&gt; {22918} 0.007075834 0.9787234  0.007229657
## [2]  {22916, 22917, 22921} =&gt; {22918} 0.007537302 0.9735099  0.007742399
## [3]  {22917, 22919, 22921} =&gt; {22918} 0.007127109 0.9720280  0.007332205
## [4]  {22917, 22918, 22921} =&gt; {22916} 0.007537302 0.9545455  0.007896221
## [5]  {22917, 22918, 22919} =&gt; {22921} 0.007127109 0.8424242  0.008460237
## [6]  {22916, 22918, 22921} =&gt; {22917} 0.007537302 0.9607843  0.007844947
## [7]  {22916, 22921}        =&gt; {22918} 0.007844947 0.9562500  0.008203866
## [8]  {22917, 22918, 22920} =&gt; {22916} 0.007844947 0.9444444  0.008306414
## [9]  {22917, 22919, 22920} =&gt; {22916} 0.007434754 0.9415584  0.007896221
## [10] {22917, 22918, 22919} =&gt; {22916} 0.007896221 0.9333333  0.008460237
## [11] {22916, 22918, 22919} =&gt; {22921} 0.007075834 0.8263473  0.008562785
## [12] {22916, 22921}        =&gt; {22917} 0.007742399 0.9437500  0.008203866
## [13] {22916, 22919, 22920} =&gt; {22917} 0.007434754 0.9415584  0.007896221
## [14] {22916, 22918, 22920} =&gt; {22917} 0.007844947 0.9386503  0.008357689
## [15] {22916, 22917, 22919} =&gt; {22918} 0.007896221 0.9333333  0.008460237
## [16] {22916, 22917, 22918} =&gt; {22921} 0.007537302 0.8166667  0.009229349
## [17] {22916, 22919, 22920} =&gt; {22918} 0.007332205 0.9285714  0.007896221
## [18] {22917, 22921}        =&gt; {22918} 0.007896221 0.9277108  0.008511511
## [19] {22917, 22918}        =&gt; {22916} 0.009229349 0.9183673  0.010049736
## [20] {22916, 22919}        =&gt; {22918} 0.008562785 0.9226519  0.009280623
## [21] {22916, 22918, 22919} =&gt; {22917} 0.007896221 0.9221557  0.008562785
## [22] {22917, 22921}        =&gt; {22916} 0.007742399 0.9096386  0.008511511
## [23] {22917, 22919, 22920} =&gt; {22918} 0.007229657 0.9155844  0.007896221
## [24] {22917, 22919}        =&gt; {22916} 0.008460237 0.9065934  0.009331898
## [25] {22917, 22920}        =&gt; {22916} 0.008614059 0.9032258  0.009536994
## [26] {22916, 22917, 22920} =&gt; {22918} 0.007844947 0.9107143  0.008614059
## [27] {22916, 22918}        =&gt; {22917} 0.009229349 0.9137056  0.010101010
## [28] {22916, 22920}        =&gt; {22917} 0.008614059 0.9130435  0.009434446
## [29] {22916, 22919}        =&gt; {22917} 0.008460237 0.9116022  0.009280623
## [30] {22918, 22919, 22920} =&gt; {22916} 0.007332205 0.8993711  0.008152592
## [31] {22917, 22919}        =&gt; {22918} 0.008460237 0.9065934  0.009331898
## [32] {22919, 22921}        =&gt; {22918} 0.007947495 0.9064327  0.008767882
## [33] {22918, 22919}        =&gt; {22921} 0.007947495 0.7948718  0.009998462
## [34] {22917, 22918, 22921} =&gt; {22919} 0.007127109 0.9025974  0.007896221
## [35] {22916, 22918, 22921} =&gt; {22919} 0.007075834 0.9019608  0.007844947
##      lift     count
## [1]  80.20186 138  
## [2]  79.77464 147  
## [3]  79.65320 139  
## [4]  78.88347 147  
## [5]  78.61148 139  
## [6]  78.40241 147  
## [7]  78.36027 153  
## [8]  78.04873 153  
## [9]  77.81023 145  
## [10] 77.13051 154  
## [11] 77.11125 138  
## [12] 77.01237 151  
## [13] 76.83353 145  
## [14] 76.59622 153  
## [15] 76.48235 154  
## [16] 76.20789 147  
## [17] 76.09214 143  
## [18] 76.02162 154  
## [19] 75.89372 180  
## [20] 75.60706 167  
## [21] 75.25022 154  
## [22] 75.17238 151  
## [23] 75.02791 141  
## [24] 74.92073 165  
## [25] 74.64243 168  
## [26] 74.62883 153  
## [27] 74.56067 180  
## [28] 74.50664 168  
## [29] 74.38903 165  
## [30] 74.32387 143  
## [31] 74.29114 165  
## [32] 74.27797 155  
## [33] 74.17409 155  
## [34] 73.96369 139  
## [35] 73.91152 138</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>retail_hi_lift_stock <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(retail_rules_stock, <span class="at">by =</span> <span class="st">&#39;lift&#39;</span>),<span class="dv">50</span>)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(retail_hi_lift_stock,<span class="at">method =</span> <span class="st">&#39;graph&#39;</span>,<span class="at">col =</span> <span class="st">&#39;blue&#39;</span>,<span class="at">cex =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Available control parameters (with default values):
## layout    =  stress
## circular  =  FALSE
## ggraphdots    =  NULL
## edges     =  &lt;environment&gt;
## nodes     =  &lt;environment&gt;
## nodetext  =  &lt;environment&gt;
## colors    =  c(&quot;#EE0000FF&quot;, &quot;#EEEEEEFF&quot;)
## engine    =  ggplot2
## max   =  100
## verbose   =  FALSE</code></pre>
<p><img src="project_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemFrequencyPlot</span>(retail_trans_stock,<span class="at">topN=</span><span class="dv">30</span>,<span class="at">type =</span> <span class="st">&#39;absolut&#39;</span>,<span class="at">horiz =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="project_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
